version: "3.9"

services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "3000:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    depends_on:
      - wp_first
      - wp_second
      - wp_third

  wp_first:
    image: wordpress:6.1.1-php7.4-fpm-alpine
    volumes:
      - ./html:/var/www/html
    env_file:
      - ./.docker/env_files/wordpress.env
    depends_on:
      - mysql

  wp_second:
    image: wordpress:6.1.1-php7.4-fpm-alpine
    volumes:
      - ./html:/var/www/html
    env_file:
      - ./.docker/env_files/wordpress.env
    depends_on:
      - mysql

  wp_third:
    image: wordpress:6.1.1-php7.4-fpm-alpine
    volumes:
      - ./html:/var/www/html
    env_file:
      - ./.docker/env_files/wordpress.env
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.28
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    env_file:
      - ./.docker/env_files/mysql.env
